name: Generate JavaDocs

on:
  push:
    branches:
      - ak

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Generate JavaDocs
      run: javadoc -d docs -sourcepath . -subpackages .

    - name: Commit JavaDocs
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git checkout -b docs
        git add docs
        git commit -m "Generate JavaDocs"
        git push origin docs
